# Generated by Django 4.1.5 on 2023-01-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=250)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
